version: '3.4'

services:
  dronemaintenance.api:
    image: ${DOCKER_REGISTRY-}dronemaintenanceapi
    build:
      context: .
      dockerfile: DroneMaintenance.API/Dockerfile
    ports:
        - "5000:80"
        - "5001:443"
    depends_on:
            - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"